export const SET_CURRENT_RETAILER = 'SET_CURRENT_RETAILER';
export const CLEAR_CURRENT_RETAILER = 'CLEAR_CURRENT_RETAILER';
export const SET_CURRENT_COMPANY = 'SET_CURRENT_COMPANY';
export const CLEAR_CURRENT_COMPANY = 'CLEAR_CURRENT_COMPANY';
